### ISSUE TITLE
Steam not starting

### ISSUE THREAD

**Issue by bratekarate** [igo95862/bubblejail#19] opened 2022-03-05 01:11 UTC
I created a sandbox for steam as follows:

```
bubblejail create --profile steam SteamInstance
```
But it does not complete to launch when I run:

```
bubblejail run SteamInstance
```
No GUI launches, here is the only output:

```
b'bin_steam.sh[2]: Setting up Steam content in /home/user/.local/share/Steam\n'
b'steam.sh[2]: Running Steam on Linux 5.16.12-artix1-1 64-bit\n'
b'steam.sh[2]: STEAM_RUNTIME is enabled automatically\n'
b'setup.sh[77]: Updating Steam runtime environment...\n'
b'\n'
b"(zenity:85): dbind-WARNING **: 01:57:40.788: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-4blON0b17C: No such file or directory\n"
b"steam.sh[2]: Can't find 'steam-runtime-check-requirements', continuing anyway\n"
b'Installing breakpad exception handler for appid(steam)/version(0)\n'
```
Waited for a about 15 minutes, but nothing seems to happen. The firefox profile works without an issue, and steam without bubblejail launches as expected.

**Comment by igo95862** [comment] 2022-03-05 07:32
Can you try running a shell and launching steam manually?

To run shell:

```
bubblejail run --debug-shell SteamInstance
```

Run steam manually:

```
steam
```

**Comment by bratekarate** [comment] 2022-03-07 12:44
I already started steam manually, it logs the same output -- except for the "Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-4blON0b17C". I don't think this is the issue though, the accessibility pipeline should not be important.

It then proceeds to start normally. I will try to use the debug shell next and report the results. Thanks for replying.

**Comment by bratekarate** [comment] 2022-04-09 00:05
Tried with debug shell, there is some more logs:

```
steam.sh[4]: Running Steam on Linux 5.17.1-artix1-1 64-bit
steam.sh[4]: STEAM_RUNTIME is enabled automatically
setup.sh[70]: Steam runtime environment up-to-date!
steam.sh[4]: Can't find 'steam-runtime-check-requirements', continuing anyway
[2022-04-09 02:03:13] Startup - updater built Nov 22 2021 22:06:59
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
Installing breakpad exception handler for appid(steam)/version(0)
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
```

**Comment by igo95862** [comment] 2022-04-09 08:23
So it is Nvidia problem?

I won't be able to really test it then. Maybe try to use `strace -ff` to track if steam is trying to access something under `/sys` and fails because it does not exists.

**Comment by bratekarate** [comment] 2022-04-09 10:03
Not sure. I am on a PRIME laptop with optimus-manager. Not sure what the implications are.

GLX seems to have issues in all instances. Firefox log:

```
b'[GFX1-]: glxtest: libEGL initialize failed\n'
b'[GFX1-]: glxtest: X error, error_code=2, request_code=152, minor_code=3\n'
b'[GFX1-]: More than 1 GPU vendor detected via PCI, cannot deduce vendor\n'
b'[GFX1-]: PCI candidate 0x10de/0x11fc\n'
b'[GFX1-]: PCI candidate 0x8086/0x0416\n'
b'[GFX1-]: glxtest: process failed (exited with status 1)\n'
```

**Comment by igo95862** [comment] 2022-04-09 13:42
> Any experience with optimus-manager and bubblejail?

No. My only laptop only has integrated Intel graphics.

**Comment by gnusenpai** [comment] 2022-04-16 08:14
This appears to be a problem unique to how the NVIDIA driver handles OpenGL/Vulkan acceleration.
I got both to work by running `bubblejail run --debug-bwrap-args dev-bind /dev /dev --debug-shell -- instance`, and confirmed working acceleration with glxinfo, glxgears, vkcube, and firefox.
Preliminary testing shows that you can also create a dev-bind for `/dev/nvidia*` (except for `nvidiactl`, it wasn't necessary in my case), but regular binds do not work.
I even got MangoHud working by adding `/sys` to the "read only paths" under "Root share", which may be of interest.
Maybe there should be a dev-bind and/or NVIDIA GPU option added to bubblejail? Or at least some way to persistently define custom bwrap arguments?

**Comment by igo95862** [comment] 2022-04-16 12:29
@gnusenpai can you do `strace` to trace what `/dev/` devices it accesses? I can add an option for DRI service to pass extra Nvidia devices.

**Comment by gnusenpai** [comment] 2022-04-16 17:56
> @gnusenpai can you do `strace` to trace what `/dev/` devices it accesses?

Here are the list of devices that NVIDIA needs for Vulkan and OpenGL:
```
/dev/dri/card0
/dev/dri/card1
/dev/dri/renderD128
/dev/dri/renderD129
/dev/nvidia0
/dev/nvidia1
/dev/nvidiactl
/dev/nvidia-modeset
```
All opened as RW.
Note that my system has 2 video cards and all of `/dev/nvidia[0-9]*` will need to be passed through.
I tested that dev-binding those specific devices works as expected. `/dev/dri` doesn't seem to be strictly necessary, but it's probably a good idea to include it, so adding an NVIDIA option under Direct Rendering seems like a good way to me.

**Comment by igo95862** [comment] 2022-04-16 19:11
@gnusenpai thank you.  Would you mind testing this patch?

```patch
index a355b1c..2a93bb0 100644
--- a/bubblejail/services.py
+++ b/bubblejail/services.py
@@ -675,6 +675,13 @@ class DirectRendering(BubblejailService):
         if self.enable_aco.get_value():
             yield EnvrimentalVar('RADV_PERFTEST', 'aco')
 
+        # Nvidia specifc binds
+        yield DevBindTry('/dev/nvidiactl')
+        yield DevBindTry('/dev/nvidia-modeset')
+        for x in Path('/dev/').iterdir():
+            if x.startswith('nvidia'):
+                yield DevBind(str(x))
+
     name = 'direct_rendering'
     pretty_name = 'Direct Rendering'
     description = 'Provides access to GPU'

```

**Comment by gnusenpai** [comment] 2022-04-16 20:50
> @gnusenpai thank you. Would you mind testing this patch?

I had to make a minor change to the for loop to make it work. It also binds everything it should on its own, so explicit binds for `nvidiactl` and `nvidia-modeset` won't be necessary.

```diff
index a355b1c..c16cc56 100644
--- a/bubblejail/services.py
+++ b/bubblejail/services.py
@@ -675,6 +675,11 @@ class DirectRendering(BubblejailService):
         if self.enable_aco.get_value():
             yield EnvrimentalVar('RADV_PERFTEST', 'aco')

+        # Nvidia specifc binds
+        for x in Path('/dev/').iterdir():
+            if str(x).startswith('/dev/nvidia'):
+                yield DevBind(str(x))
+
     name = 'direct_rendering'
     pretty_name = 'Direct Rendering'
     description = 'Provides access to GPU'
```

**Comment by igo95862** [comment] 2022-04-17 09:34
I pushed f7086f931a666596ae7215407312e84563952794 . @bratekarate can you give it a test?

**Comment by bratekarate** [comment] 2022-04-17 23:07
@igo95862 Yes it works, thank you! Before your commit I could only get it running with debug args from comand line but it did not work with .desktop file. Now everything seems to work fine!

**Comment by igo95862** [comment] 2022-04-19 17:45
0.5.3 released with the fix

**Closed by igo95862** 2022-04-19 17:45 UTC
